use ratatui::style::{Color, Modifier, Style};
use ratatui::text::{Line, Span};

use crate::config::ThemeConfig;
use crate::content::ContentBlock;

// ---------------------------------------------------------------------------
// Data model
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub enum Role {
    User,
    Agent,
}

#[derive(Debug, Clone)]
pub struct ChatMessage {
    pub role: Role,
    pub timestamp: String,
    pub model: Option<String>,
    pub content: String,
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

const SPECSTORY_HEADER: &str = "<!-- Generated by SpecStory";

pub fn is_specstory(input: &str) -> bool {
    input.trim_start().starts_with(SPECSTORY_HEADER)
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

/// Parse a SpecStory markdown file into a list of chat messages.
pub fn parse_specstory(input: &str) -> Vec<ChatMessage> {
    split_into_messages(input)
}

/// Split input into sections by `---` horizontal rules AND by role headers
/// (`_**User ...**_` / `_**Agent ...**_`), since multiple consecutive agent
/// messages can appear within a single `---` section.
fn split_into_messages(input: &str) -> Vec<ChatMessage> {
    let mut messages = Vec::new();
    let mut current_header: Option<(Role, String, Option<String>)> = None;
    let mut current_content = String::new();

    for line in input.lines() {
        let stripped = line.trim();

        // Skip HR separators
        if stripped == "---" || stripped == "***" || stripped == "___" {
            continue;
        }

        // Check if this line is a role header
        if let Some(parsed) = try_parse_header(stripped) {
            // Flush previous message
            if let Some((role, timestamp, model)) = current_header.take() {
                let content = current_content.trim().to_string();
                if !content.is_empty() {
                    messages.push(ChatMessage {
                        role,
                        timestamp,
                        model,
                        content,
                    });
                }
            }
            current_header = Some(parsed);
            current_content.clear();
        } else if current_header.is_some() {
            if !current_content.is_empty() {
                current_content.push('\n');
            }
            current_content.push_str(line);
        }
    }

    // Flush last message
    if let Some((role, timestamp, model)) = current_header {
        let content = current_content.trim().to_string();
        if !content.is_empty() {
            messages.push(ChatMessage {
                role,
                timestamp,
                model,
                content,
            });
        }
    }

    messages
}

fn try_parse_header(line: &str) -> Option<(Role, String, Option<String>)> {
    let inner = line.strip_prefix("_**")?.strip_suffix("**_")?;

    let (role, rest) = if let Some(rest) = inner.strip_prefix("User") {
        (Role::User, rest.trim())
    } else if let Some(rest) = inner.strip_prefix("Agent") {
        (Role::Agent, rest.trim())
    } else {
        return None;
    };

    let (timestamp, model) = parse_role_meta(rest, &role);
    Some((role, timestamp, model))
}

fn parse_role_meta(meta: &str, role: &Role) -> (String, Option<String>) {
    // meta is like "(2025-12-03T08:19:20.239Z)" or "(model-name 2025-12-03T08:20:15.123Z)"
    let inner = meta
        .strip_prefix('(')
        .and_then(|s| s.strip_suffix(')'))
        .unwrap_or(meta)
        .trim();

    match role {
        Role::User => (inner.to_string(), None),
        Role::Agent => {
            // For agent, the model name comes before the timestamp
            // Timestamp looks like an ISO date: YYYY-MM-DD...
            if let Some(ts_start) = find_timestamp_start(inner) {
                let model = inner[..ts_start].trim().to_string();
                let timestamp = inner[ts_start..].trim().to_string();
                let model = if model.is_empty() {
                    None
                } else {
                    Some(model)
                };
                (timestamp, model)
            } else {
                (inner.to_string(), None)
            }
        }
    }
}

fn find_timestamp_start(s: &str) -> Option<usize> {
    // Look for YYYY-MM-DD pattern
    for (i, _) in s.char_indices() {
        if s.len() >= i + 10 {
            let candidate = &s[i..i + 10];
            if candidate.len() == 10
                && candidate.as_bytes()[4] == b'-'
                && candidate.as_bytes()[7] == b'-'
                && candidate[..4].chars().all(|c| c.is_ascii_digit())
                && candidate[5..7].chars().all(|c| c.is_ascii_digit())
                && candidate[8..10].chars().all(|c| c.is_ascii_digit())
            {
                return Some(i);
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

pub fn render_specstory(
    input: &str,
    theme: &ThemeConfig,
    width: u16,
) -> Vec<ContentBlock> {
    let messages = parse_specstory(input);
    if messages.is_empty() {
        return vec![ContentBlock::Text {
            lines: vec![Line::from(Span::styled(
                "No messages found in SpecStory file.",
                Style::default().fg(theme.blockquote.0),
            ))],
        }];
    }

    let width = width.max(20) as usize;
    let mut all_lines: Vec<Line<'static>> = Vec::new();

    // Title line
    all_lines.push(Line::from(Span::styled(
        "SpecStory Conversation",
        Style::default()
            .fg(theme.heading1.0)
            .add_modifier(Modifier::BOLD),
    )));
    all_lines.push(Line::from(""));

    for msg in &messages {
        let bubble_lines = render_bubble(msg, width, theme);
        all_lines.extend(bubble_lines);
        all_lines.push(Line::from("")); // spacing between messages
    }

    vec![ContentBlock::Text { lines: all_lines }]
}

fn render_bubble(
    msg: &ChatMessage,
    width: usize,
    _theme: &ThemeConfig,
) -> Vec<Line<'static>> {
    let is_user = msg.role == Role::User;

    // Bubble styling — distinct colors for user vs agent
    let (border_color, header_color, content_color, label) = if is_user {
        (Color::Blue, Color::LightBlue, Color::White, "You")
    } else {
        (Color::Green, Color::LightGreen, Color::Rgb(200, 200, 220), "Agent")
    };

    let border_style = Style::default().fg(border_color);
    let header_style = Style::default()
        .fg(header_color)
        .add_modifier(Modifier::BOLD);
    let content_style = Style::default().fg(content_color);

    // Build header text
    let header_text = if let Some(ref model) = msg.model {
        format!("{label} ({model})")
    } else {
        label.to_string()
    };

    let timestamp_short = shorten_timestamp(&msg.timestamp);

    // Full-width bubbles (borders "│ " + " │" = 4 chars)
    let bubble_outer = width;
    let bubble_inner = bubble_outer.saturating_sub(4).max(10);

    // Process content: collapse <think> and tool-use blocks
    let processed = collapse_special_blocks(&msg.content);

    // Word-wrap content lines
    let wrapped = wrap_text(&processed, bubble_inner);

    let mut lines: Vec<Line<'static>> = Vec::new();

    // Top border with styled header
    lines.push(Line::from(build_header_spans(
        &header_text,
        &timestamp_short,
        bubble_outer,
        border_style,
        header_style,
    )));

    // Content lines
    for content_line in &wrapped {
        let visible_len = char_width(content_line);
        let padding = bubble_inner.saturating_sub(visible_len);
        lines.push(Line::from(vec![
            Span::styled("│ ".to_string(), border_style),
            Span::styled(
                format!("{}{}", content_line, " ".repeat(padding)),
                content_style,
            ),
            Span::styled(" │".to_string(), border_style),
        ]));
    }

    // Bottom border: ╰─────╯
    let bottom_border = format!(
        "╰{}╯",
        "─".repeat(bubble_outer.saturating_sub(2).max(0))
    );
    lines.push(Line::from(Span::styled(bottom_border, border_style)));

    lines
}

fn build_header_spans(
    header_text: &str,
    timestamp: &str,
    bubble_outer: usize,
    border_style: Style,
    header_style: Style,
) -> Vec<Span<'static>> {
    let header_part = format!(" {} ", header_text);
    let ts_part = format!("{} ", timestamp);
    let used = 2 + char_width(&header_part) + char_width(&ts_part) + 1; // "╭─" + header + ts + "╮"
    let fill = bubble_outer.saturating_sub(used);

    vec![
        Span::styled("╭─".to_string(), border_style),
        Span::styled(header_part, header_style),
        Span::styled(
            format!("{}{}", "─".repeat(fill.max(0)), ts_part),
            Style::default().fg(Color::DarkGray),
        ),
        Span::styled("╮".to_string(), border_style),
    ]
}

fn shorten_timestamp(ts: &str) -> String {
    // Convert "2025-12-03T08:19:20.239Z" to "12-03 08:19"
    if ts.len() >= 16 && ts.contains('T') {
        let date_part = &ts[5..10]; // MM-DD
        let time_part = &ts[11..16]; // HH:MM
        format!("{date_part} {time_part}")
    } else if ts.len() >= 10 {
        ts[..10].to_string()
    } else {
        ts.to_string()
    }
}

fn collapse_special_blocks(content: &str) -> String {
    let mut result = String::new();
    let mut in_think = false;
    let mut in_tool_use = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed == "<think>" || trimmed.starts_with("<think>") {
            in_think = true;
            result.push_str("[thinking...]\n");
            continue;
        }
        if trimmed == "</think>" || trimmed.ends_with("</think>") {
            in_think = false;
            continue;
        }
        if in_think {
            continue;
        }

        if trimmed.starts_with("<tool_use>")
            || trimmed.starts_with("<tool-use")
            || trimmed.starts_with("<execute_command>")
            || trimmed.starts_with("<read_file>")
            || trimmed.starts_with("<write_to_file>")
            || trimmed.starts_with("<search_files>")
            || trimmed.starts_with("<list_files>")
            || trimmed.starts_with("<apply_diff>")
        {
            in_tool_use = true;
            // Extract tool name from data-tool-name="..." or tag name
            let tag_name = if let Some(name_start) = trimmed.find("data-tool-name=\"") {
                let after = &trimmed[name_start + 16..];
                after.split('"').next().unwrap_or("tool")
            } else {
                trimmed
                    .trim_start_matches('<')
                    .split(|c: char| c == '>' || c.is_whitespace())
                    .next()
                    .unwrap_or("tool")
            };
            result.push_str(&format!("[tool: {tag_name}]\n"));
            continue;
        }
        if in_tool_use {
            // Check for closing tags (</tool_use>, </tool-use>, </details>, etc.)
            if (trimmed.starts_with("</") && trimmed.ends_with('>'))
                || trimmed == "</details>"
            {
                in_tool_use = false;
            }
            continue;
        }

        result.push_str(line);
        result.push('\n');
    }

    result.trim_end().to_string()
}

fn char_width(s: &str) -> usize {
    // Count display width: ASCII chars = 1, CJK/wide chars = 2, others = 1
    s.chars()
        .map(|c| if unicode_width::UnicodeWidthChar::width(c).unwrap_or(0) > 1 { 2 } else { 1 })
        .sum()
}

fn wrap_text(text: &str, max_width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    for line in text.lines() {
        if line.is_empty() {
            lines.push(String::new());
            continue;
        }
        if char_width(line) <= max_width {
            lines.push(line.to_string());
        } else {
            // Simple word wrap
            let mut current = String::new();
            let mut current_width = 0usize;
            for word in line.split_whitespace() {
                let word_width = char_width(word);
                if current.is_empty() {
                    if word_width > max_width {
                        // Force break long words by characters
                        let mut buf = String::new();
                        let mut buf_width = 0usize;
                        for ch in word.chars() {
                            let cw = unicode_width::UnicodeWidthChar::width(ch).unwrap_or(1).max(1);
                            if buf_width + cw > max_width && !buf.is_empty() {
                                lines.push(buf);
                                buf = String::new();
                                buf_width = 0;
                            }
                            buf.push(ch);
                            buf_width += cw;
                        }
                        current = buf;
                        current_width = buf_width;
                    } else {
                        current = word.to_string();
                        current_width = word_width;
                    }
                } else if current_width + 1 + word_width <= max_width {
                    current.push(' ');
                    current.push_str(word);
                    current_width += 1 + word_width;
                } else {
                    lines.push(current);
                    current = word.to_string();
                    current_width = word_width;
                }
            }
            if !current.is_empty() {
                lines.push(current);
            }
        }
    }
    lines
}


// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"<!-- Generated by SpecStory, Markdown v2.0.0 -->
# 2025-12-03 08:19:20.239Z

_**User (2025-12-03T08:19:20.239Z)**_
Hello, can you help me?

---

_**Agent (claude-3-opus 2025-12-03T08:20:15.123Z)**_
Of course! How can I assist you today?

---

_**User (2025-12-03T08:21:00.000Z)**_
Fix the bug in main.rs

---

_**Agent (claude-3-opus 2025-12-03T08:22:00.000Z)**_
<think>
Let me analyze the code...
</think>

I found the issue. Here's the fix:

```rust
fn main() {
    println!("fixed");
}
```
"#;

    #[test]
    fn test_is_specstory() {
        assert!(is_specstory(SAMPLE));
        assert!(!is_specstory("# Regular markdown"));
        assert!(!is_specstory(""));
    }

    #[test]
    fn test_parse_specstory_message_count() {
        let messages = parse_specstory(SAMPLE);
        assert_eq!(messages.len(), 4);
    }

    #[test]
    fn test_parse_specstory_roles() {
        let messages = parse_specstory(SAMPLE);
        assert_eq!(messages[0].role, Role::User);
        assert_eq!(messages[1].role, Role::Agent);
        assert_eq!(messages[2].role, Role::User);
        assert_eq!(messages[3].role, Role::Agent);
    }

    #[test]
    fn test_parse_specstory_model() {
        let messages = parse_specstory(SAMPLE);
        assert_eq!(messages[0].model, None);
        assert_eq!(messages[1].model, Some("claude-3-opus".to_string()));
    }

    #[test]
    fn test_parse_specstory_timestamp() {
        let messages = parse_specstory(SAMPLE);
        assert_eq!(messages[0].timestamp, "2025-12-03T08:19:20.239Z");
    }

    #[test]
    fn test_parse_specstory_content() {
        let messages = parse_specstory(SAMPLE);
        assert_eq!(messages[0].content, "Hello, can you help me?");
        assert!(messages[1]
            .content
            .contains("Of course! How can I assist you today?"));
    }

    #[test]
    fn test_collapse_think_blocks() {
        let input = "Before\n<think>\nsome reasoning\n</think>\nAfter";
        let result = collapse_special_blocks(input);
        assert!(result.contains("[thinking...]"));
        assert!(!result.contains("some reasoning"));
        assert!(result.contains("After"));
    }

    #[test]
    fn test_collapse_tool_use_blocks() {
        let input = "Before\n<execute_command>\nsome command\n</execute_command>\nAfter";
        let result = collapse_special_blocks(input);
        assert!(result.contains("[tool: execute_command]"));
        assert!(!result.contains("some command"));
        assert!(result.contains("After"));
    }

    #[test]
    fn test_collapse_tool_use_with_data_attr() {
        let input = "Before\n<tool-use data-tool-type=\"unknown\" data-tool-name=\"Agent\"><details>\n<summary>Tool use</summary>\nstuff\n</details>\nAfter";
        let result = collapse_special_blocks(input);
        assert!(result.contains("[tool: Agent]"));
        assert!(!result.contains("stuff"));
        assert!(result.contains("After"));
    }

    #[test]
    fn test_shorten_timestamp() {
        assert_eq!(
            shorten_timestamp("2025-12-03T08:19:20.239Z"),
            "12-03 08:19"
        );
    }

    #[test]
    fn test_wrap_text() {
        let wrapped = wrap_text("hello world this is a test", 10);
        assert!(wrapped.iter().all(|l| l.len() <= 10));
        assert!(wrapped.len() >= 3);
    }
}
